# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pre-processing.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14pre-processing.proto\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1f\n\rImageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2?\n\x0cImageService\x12/\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pre_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=24
  _globals['_IMAGEREQUEST']._serialized_end=53
  _globals['_IMAGERESPONSE']._serialized_start=55
  _globals['_IMAGERESPONSE']._serialized_end=86
  _globals['_IMAGESERVICE']._serialized_start=88
  _globals['_IMAGESERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
